INSERT INTO USERS (ID, FIRST_NAME, LAST_NAME, EMAIL, USERNAME, PASSWORD, IS_ACTIVE)
VALUES (1, 'John', 'Doe', 'admin@example.org', 'john', '$2a$10$A/wEMEFuo.ZhAZMYQiXbrOjlOJ0K0jDxom5wDNV5EmvELYV59XMga', TRUE)
;

INSERT INTO USERS_ACCESS_RIGHTS (USER_ID, CREATE_ACCESS, READ_ACCESS, UPDATE_ACCESS, DELETE_ACCESS)
VALUES (1, TRUE, TRUE, TRUE, TRUE)
;

INSERT INTO USERS (ID, FIRST_NAME, LAST_NAME, EMAIL, USERNAME, PASSWORD, IS_ACTIVE)
VALUES (2, 'John', 'Wick', 'admin@admin.org', 'jwick', '$2a$10$A/wEMEFuo.ZhAZMYQiXbrOjlOJ0K0jDxom5wDNV5EmvELYV59XMga', TRUE)
;

INSERT INTO USERS_ACCESS_RIGHTS (USER_ID, CREATE_ACCESS, READ_ACCESS, UPDATE_ACCESS, DELETE_ACCESS)
VALUES (2, FALSE, TRUE, FALSE , FALSE)
;

