CREATE TABLE `USERS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `FIRST_NAME` varchar(50) NOT NULL,
  `LAST_NAME` varchar(50) NOT NULL,
  `EMAIL` varchar(50) NOT NULL,
  `USERNAME` varchar(30) NOT NULL,
  `PASSWORD` text NOT NULL,
  `IS_ACTIVE` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`ID`,`EMAIL`,`USERNAME`),
  UNIQUE KEY `EMAIL` (`EMAIL`),
  UNIQUE KEY `USERNAME` (`USERNAME`)
  )
  ;

CREATE TABLE `USERS_ACCESS_RIGHTS` (
  `USER_ID` int(11) NOT NULL,
  `CREATE_ACCESS` tinyint(1) DEFAULT NULL,
  `READ_ACCESS` tinyint(1) DEFAULT NULL,
  `UPDATE_ACCESS` tinyint(1) DEFAULT NULL,
  `DELETE_ACCESS` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`USER_ID`),
  UNIQUE KEY `USER_ID` (`USER_ID`),
  FOREIGN KEY (`USER_ID`) REFERENCES `USERS` (`ID`) ON DELETE CASCADE
  )
  ;

  INSERT INTO USERS (ID, FIRST_NAME, LAST_NAME, EMAIL, USERNAME, PASSWORD, IS_ACTIVE)
  VALUES (1, 'John', 'Doe', 'admin@example.org', 'john', '$2a$10$32Hw5zY7uvx0EgsfE/yQNuuL.Nrt5srepNP.vlmES2VKbYAnOBqC6', TRUE)
  ;

  INSERT INTO USERS_ACCESS_RIGHTS (USER_ID, CREATE_ACCESS, READ_ACCESS, UPDATE_ACCESS, DELETE_ACCESS)
  VALUES (1, TRUE, TRUE, TRUE, TRUE)
  ;

  INSERT INTO USERS (ID, FIRST_NAME, LAST_NAME, EMAIL, USERNAME, PASSWORD, IS_ACTIVE)
  VALUES (2, 'John', 'Wick', 'admin@admin.org', 'jwick', '$2a$10$32Hw5zY7uvx0EgsfE/yQNuuL.Nrt5srepNP.vlmES2VKbYAnOBqC6', TRUE)
  ;

  INSERT INTO USERS_ACCESS_RIGHTS (USER_ID, CREATE_ACCESS, READ_ACCESS, UPDATE_ACCESS, DELETE_ACCESS)
  VALUES (2, FALSE, TRUE, FALSE , FALSE)
  ;

